(function(){'use strict';var l,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var ca=ba(this),q;
if("function"==typeof Object.setPrototypeOf)q=Object.setPrototypeOf;else{var t;a:{var da={a:!0},v={};try{v.__proto__=da;t=v.a;break a}catch(a){}t=!1}q=t?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var w=q;var ea={C:0,D:0,F:0,G:0,H:"#fff",I:"#fff",J:0,v:0,m:0,K:"0px",L:"0px",M:"0px",N:"0px",loop:!1,O:0,P:1,R:1,S:0,T:!1,shape:"square",V:1,W:1,X:0,Y:0,s:0,u:0,ea:"",U:!1,B:1,Z:0,l:1,aa:1},fa={C:0,D:0,F:280,G:260,H:"#fff",I:"#fff",J:0,v:.005,m:2,K:"100%",L:"0%",M:"10%",N:"0%",loop:!0,O:0,P:1,R:.1,S:0,T:!0,shape:"circle",V:12,W:8,X:0,Y:0,s:2,u:1,ea:"",U:!1,B:1,Z:0,l:1,aa:1},ha={C:0,D:.6,F:271,G:269,H:"#fff",I:"#fff",J:0,v:.01,m:2,K:"100%",L:"0%",M:"10%",N:"0%",loop:!0,O:0,P:1,R:.5,S:0,T:!0,shape:"line",
V:25,W:10,X:0,Y:100,s:10,u:8,ea:"",U:!1,B:1,Z:0,l:1,aa:1},ia={C:0,D:.6,F:100,G:80,H:"#ffdc00",I:"#dc000a",J:1.2,v:0,m:1,K:"20px",L:"10px",M:"40px",N:"35px",loop:!0,O:10,P:.3,R:.1,S:-.3,T:!1,shape:"teardrop",V:20,W:20,X:-30,Y:100,s:1,u:.5,ea:"",U:!0,B:20,Z:.18,l:1,aa:30},ja={C:0,D:.6,F:100,G:80,H:"#ffdc00",I:"#dc000a",J:1,v:0,m:2,K:"50px",L:"20px",M:"100px",N:"95px",loop:!0,O:15,P:.3,R:.1,S:-.3,T:!1,shape:"teardrop",V:40,W:40,X:-30,Y:100,s:2,u:1,ea:"",U:!0,B:20,Z:.18,l:1,aa:30},ka={C:0,D:.6,F:100,
G:80,H:"#ffdc00",I:"#dc000a",J:.8,v:0,m:4,K:"80px",L:"30px",M:"180px",N:"175px",loop:!0,O:15,P:.3,R:.1,S:-.3,T:!1,shape:"teardrop",V:100,W:100,X:-54,Y:100,s:3,u:2,ea:"",U:!0,B:20,Z:.18,l:1,aa:25},la={C:0,D:0,F:90,G:90,H:"#dcdcdc",I:"#dcdcdc",J:0,v:0,m:25,K:"22px",L:"10px",M:"120px",N:"100px",loop:!0,O:8,P:.03,R:.03,S:-.018,T:!0,shape:"teardrop",V:15,W:15,X:-.06,Y:100,s:1,u:.8,ea:"",U:!0,B:60,Z:.6,l:.5,aa:40},ma={C:0,D:.06,F:100,G:80,H:"#dcdcdc",I:"#dcdcdc",J:0,v:0,m:2,K:"35px",L:"10px",M:"150px",
N:"148px",loop:!0,O:300,P:.1,R:.1,S:-.03,T:!0,shape:"circle",V:20,W:10,X:-1.2,Y:100,s:.8,u:.8,ea:"",U:!0,B:10,Z:0,l:.5,aa:1};function x(a,b,d){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=d);return a}function B(a,b,d){a=x(a,b,d);return 0<a?a:d}function C(a,b,d){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=d);return a}function D(a,b,d){return a.hasAttribute(b)?a.getAttribute(b):d}function E(a,b,d){switch(a.getAttribute(b)){case "true":return!0;case "false":return!1;default:return d}};var na=/[^\d]+$/;function F(a,b,d,c){if(!a.hasAttribute(b))return d;a=a.getAttribute(b);return isNaN(parseFloat(a))?d:H(a,c)}function H(a,b){var d=parseFloat(a);(a=(a=a.match(na))&&a[0]||null)&&(a=a.trim());var c=d;"%"==a&&(c=Number((d/100*b).toFixed(2)));return c};var oa=/^#(?:[0-9a-f]{3}){1,2}$/i,pa=/#(.)(.)(.)/,I=[60,6E3];function J(a){if(!oa.test(a))return null;4==a.length&&(a=a.replace(pa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]}function K(a,b,d,c,f){b=C(a,b,c);a=C(a,d,f);b>a&&(d=b,b=a,a=d);return[b,a]}
function qa(a){switch(a){case "snow":return fa;case "rain":return ha;case "fire-small":return ia;case "fire-medium":return ja;case "fire-large":return ka;case "steam":return la;case "smoke":return ma;default:return ea}}function L(a,b,d,c,f,e){b=F(a,b,c,e);a=F(a,d,f,e);b>a&&(d=b,b=a,a=d);return[b,a]};function M(a,b,d){return a+d*(b-a)}function P(a){return a*a*a*(a*(6*a-15)+10)}function Q(a,b,d,c){switch(a%16){case 0:return b+d;case 1:return-b+d;case 2:return b-d;case 3:return-b-d;case 4:return b+c;case 5:return-b+c;case 6:return b-c;case 7:return-b-c;case 8:return d+c;case 9:return-d+c;case 10:return d-c;case 11:return-d-c;case 12:return b+d;case 13:return-d+c;case 14:return-b+d;case 15:return-d-c;default:return 0}}
function ra(){for(var a=Array(256),b=0;b<a.length;++b)a[b]=b;for(b=a.length-1;0<b;--b){var d=Math.floor(Math.random()*a.length),c=a[b];a[b]=a[d];a[d]=c}this.g=a.concat(a)}
function R(a,b,d,c){var f=b&255,e=d&255,g=c&255;b-=Math.floor(b);d-=Math.floor(d);c-=Math.floor(c);var k=P(b),h=P(d);a=a.g;return M(M(M(Q(a[a[a[f]+e]+g],b,d,c),Q(a[a[a[f+1]+e]+g],b-1,d,c),k),M(Q(a[a[a[f]+e+1]+g],b,d-1,c),Q(a[a[a[f+1]+e+1]+g],b-1,d-1,c),k),h),M(M(Q(a[a[a[f]+e]+g+1],b,d,c-1),Q(a[a[a[f+1]+e]+g+1],b-1,d,c-1),k),M(Q(a[a[a[f]+e+1]+g+1],b,d-1,c-1),Q(a[a[a[f+1]+e+1]+g+1],b-1,d-1,c-1),k),h),P(c))};function S(a){this.j=a;this.i=[];this.length=this.g=0}S.prototype.get=function(a){return this.i[(a+this.g)%this.length]};var sa=2*Math.PI;function T(a,b){return a+Math.random()*(b-a)}
function ta(a,b){this.j=[];this.g=b;this.i=a.getContext("2d");this.Ba=window.devicePixelRatio;this.Da=1;this.Ea=[];this.Fa=[];if("image"!=this.g.pa.shape)a=null;else if((a=this.g.pa.Sa)&&0!=a.length){b=[];this.Da=this.g.oa.max*this.Ba;for(var d=0;d<a.length;d++){var c=a[d],f=document.createElement("canvas"),e=f.getContext("2d"),g=this.Da/Math.max(c.naturalWidth,c.naturalHeight),k=c.naturalWidth*g;g*=c.naturalHeight;f.width=Math.ceil(k);f.height=Math.ceil(g);e.drawImage(c,0,0,k,g);b.push(f);this.Ea.push(-k/
2);this.Fa.push(-g/2)}a=b}else this.g.pa.shape="square",a=null;this.Ca=a;this.o=0;this.Na=0==this.g.m?this.g.za:1/this.g.m;a=this.g.ga;this.xa=a.ja?0:(a.ma-a.va)*a.Aa;this.wa=a.ja?0:(a.la-a.ua)*a.Aa;this.A=a.ja?0:(a.ka-a.ta)*a.Aa;this.ra=(a=this.g.Ia)?new ra:null;this.sa=a?a.frequency:1;this.Oa=a?a.Ua:1;this.Ga=a&&a.Va-1||0;for(a=0;a<this.g.Ha;a++)U(this)}
function V(a){var b=T(a.g.na.Ka,a.g.na.Ja),d=T(a.g.na.Ma,a.g.na.La),c=T(a.g.oa.min,a.g.oa.max),f=T(a.g.ya.min,a.g.ya.max),e=a.g.ga,g=e.va,k=e.ua,h=e.ta;e.ja&&(h=Math.random(),g=(1-h)*e.va+h*e.ma,k=(1-h)*e.ua+h*e.la,h=(1-h)*e.ta+h*e.ka);var n=T(a.g.qa.u,a.g.qa.s);e=T(a.g.qa.Qa,a.g.qa.Pa);var z=n*Math.cos(e);n*=Math.sin(e);var y=-1;a.Ca&&(y=Math.floor(T(0,a.Ca.length)));return{h:{positionX:b,positionY:d,size:c,da:g,ca:k,ba:h,opacity:f,ha:!0,angle:e,ia:y},velocityX:z,velocityY:n,l:a.Oa,fa:a.Ga?new S(a.Ga):
null}}
function U(a){for(var b=Date.now()/a.sa,d=0;d<a.j.length;d++){var c=a.j[d],f=a;if(c.fa){var e=c.fa,g={positionX:c.h.positionX,positionY:c.h.positionY,size:c.h.size,da:c.h.da,ca:c.h.ca,ba:c.h.ba,opacity:c.h.opacity,angle:c.h.angle,ia:c.h.ia,ha:c.h.ha};e.length<e.j&&e.length++;e.i[e.g]=g;e.g=(e.g+1)%e.j}c.h.ha&&(c.h.positionX+=c.velocityX,c.h.positionY+=c.velocityY,f.ra&&0<c.l&&(e=c.h.positionX/f.sa,g=c.h.positionY/f.sa,c.h.positionX+=c.l*R(f.ra,e,g,b),c.h.positionY+=c.l*R(f.ra,b,e,g),c.l+=f.g.Ia.rate),c.h.size+=
f.g.oa.rate,c.h.opacity=Math.min(1,c.h.opacity+f.g.ya.rate),c.velocityX+=f.g.acceleration.x,c.velocityY+=f.g.acceleration.y,c.h.angle=Math.atan2(c.velocityY,c.velocityX),e=f.g.ga,e.ja||((!f.xa||1<(e.ma-c.h.da)/f.xa)&&(!f.wa||1<(e.la-c.h.ca)/f.wa)&&(!f.A||1<(e.ka-c.h.ba)/f.A)?(c.h.da+=f.xa,c.h.ca+=f.wa,c.h.ba+=f.A):(c.h.da=f.g.ga.ma,c.h.ca=f.g.ga.la,c.h.ba=f.g.ga.ka)));if(0>c.h.positionX+c.h.size||c.h.positionX-c.h.size>a.g.width||0>c.h.positionY+c.h.size||c.h.positionY-c.h.size>a.g.height||0>c.h.opacity||
0>c.h.size)a.g.Ta?(c=c.fa,a.j[d]=V(a),a.j[d].fa=c):c.h.ha=!1}if(a.j.length<a.g.za)for(a.o=Math.min(a.o+a.Na,a.g.za),b=Math.floor(a.o)-a.j.length,d=0;d<b;d++)a.j.push(V(a))}
function ua(a,b){if(b.ha){a.i.fillStyle="rgba("+Math.round(b.da)+", "+Math.round(b.ca)+", "+Math.round(b.ba)+", "+b.opacity+")";a.i.save();a.i.translate(b.positionX,b.positionY);var d=b.size/a.Da;a.i.scale(d,d);switch(a.g.pa.shape){case "circle":a.i.beginPath();a.i.arc(0,0,.5,0,sa);a.i.fill();break;case "line":a.i.beginPath();a.i.rotate(b.angle);a.i.fillRect(-.5,-.01,1,.02);break;case "teardrop":a.i.beginPath();a.i.moveTo(.08,-.5);a.i.bezierCurveTo(.13,-.21,.16,.04,.3,.07);a.i.bezierCurveTo(.44,.36,
.13,.5,-.06,.5);a.i.bezierCurveTo(-.49,.14,-.41,0,.08,-.5);a.i.fill();break;case "image":a.i.globalAlpha=b.opacity;a.i.drawImage(a.Ca[b.ia],a.Ea[b.ia],a.Fa[b.ia]);break;default:a.i.beginPath(),a.i.fillRect(-.5,-.5,1,1)}a.i.restore()}};function va(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")}function wa(a){if(va(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&va(a))return a;return null}function xa(a){return(a=D(a,"sprite-image-src",""))?a.split(",").map(function(b){return b.trim()}):[]};function ya(a,b){var d=void 0===d?null:d;var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,d);b.dispatchEvent(c)};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var za={Wa:"acceleration-x",Xa:"acceleration-y",Ya:"angle-max",Za:"angle-min",ab:"autoplay",bb:"color1",cb:"color2",eb:"color-rate",fb:"custom-preset",gb:"emit-interval",hb:"emit-x-max",ib:"emit-x-min",jb:"emit-y-max",kb:"emit-y-min",lb:"loop",mb:"number",nb:"opacity-max",ob:"opacity-min",pb:"opacity-rate",qb:"preset-type",rb:"random-colors",sb:"shape",tb:"size-max",ub:"size-min",vb:"size-rate",wb:"skip-forward",xb:"speed-max",yb:"speed-min",zb:"sprite-image-src",Ab:"turbulence-frequency",Bb:"turbulence-rate",
Cb:"turbulence-strength",Db:"turbulence-trail"},Aa=[],Ba=0,Ca;for(Ca in za)Aa[Ba++]=za[Ca];function W(){var a=HTMLElement.call(this)||this;a.g=null;a.j=0;a.i=[];a.o=a.Ra.bind(a);a.A=2;return a}var X=HTMLElement;W.prototype=aa(X.prototype);W.prototype.constructor=W;if(w)w(W,X);else for(var Y in X)if("prototype"!=Y)if(Object.defineProperties){var Da=Object.getOwnPropertyDescriptor(X,Y);Da&&Object.defineProperty(W,Y,Da)}else W[Y]=X[Y];l=W.prototype;l.attributeChangedCallback=function(){this.reset()};
l.connectedCallback=function(){if(!this.gwdIsLoaded()){var a=wa(this);a?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad()}};l.disconnectedCallback=function(){Z(this);this.g=null};l.gwdLoad=function(){if(!this.g){Z(this);var a=xa(this);if(this.j=a.length)for(var b=0;b<this.j;b++){var d=this.ownerDocument.createElement("img");d.addEventListener("load",this.o,!1);d.addEventListener("error",this.o,!1);d.src=a[b];this.i.push(d)}0===this.j&&Ea(this)}};l.gwdIsLoaded=function(){return!!this.g};
function Z(a){for(;a.i.length;){var b=a.i.pop();b.removeEventListener("load",a.o,!1);b.removeEventListener("error",a.o,!1)}a.j=0}
function Ea(a){var b=a.getAttribute("preset-type"),d=a.i.length?a.i:null;if(a.parentElement){var c=a.parentElement.getElementsByTagName("canvas")[0];if(c){var f=a.parentElement.clientWidth,e=a.parentElement.clientHeight;b=qa(b);var g=H(b.L,f),k=H(b.K,f);var h=H(b.N,e);var n=H(b.M,e);g=L(a,"emit-x-min","emit-x-max",g,k,f);h=L(a,"emit-y-min","emit-y-max",h,n,e);h={Ka:g[0],Ja:g[1],Ma:h[0],La:h[1]};n=b.O;b.v&&(n=Math.ceil(b.v*(h.Ja-h.Ka)*(h.La-h.Ma)));n=Math.min(B(a,"number",n),1E3);g=B(a,"emit-interval",
b.m);k=b.Y;var z=x(a,"skip-forward",k);k=Math.round((0<=z?z:k)*Math.min(Math.max(n*g,I[0]),I[1])/100);z=E(a,"loop",b.loop);var y=K(a,"size-min","size-max",b.W,b.V);var A=C(a,"size-rate",b.X)/60;y={min:y[0],max:y[1],rate:A};A=K(a,"opacity-min","opacity-max",b.R,b.P);var u=C(a,"opacity-rate",b.S)/60;A={min:A[0],max:A[1],rate:u};u=D(a,"color1",b.H);var r=D(a,"color2",b.I);u=J(u);r=J(r);var m=E(a,"random-colors",b.T),p=C(a,"color-rate",b.J)/60;u={ja:m,va:u[0],ua:u[1],ta:u[2],ma:r[0],la:r[1],ka:r[2],Aa:p};
r=K(a,"speed-min","speed-max",b.u,b.s);m=K(a,"angle-min","angle-max",b.G,b.F);m[0]=-m[0];m[1]=-m[1];r={u:r[0],s:r[1],Qa:m[1]/180*Math.PI,Pa:m[0]/180*Math.PI};m=C(a,"acceleration-x",b.C)/60;p=C(a,"acceleration-y",b.D)/60;m={x:m,y:p};p=D(a,"shape",b.shape);d={shape:p,Sa:"image"==p?d:null};p=a.hasAttribute("turbulence-frequency");var G=a.hasAttribute("turbulence-strength"),N=a.hasAttribute("turbulence-rate"),O=a.hasAttribute("turbulence-trail");b.U||p||G||N||O?(p=C(a,"turbulence-frequency",b.B),G=C(a,
"turbulence-strength",b.l),N=C(a,"turbulence-rate",b.Z)/60,O=Math.min(B(a,"turbulence-trail",b.aa),100),b={frequency:0<p?p:b.B,Ua:0<G?G:b.l,rate:N,Va:O}):b=null;a.g=new ta(c,{width:f,height:e,za:n,m:g,Ha:k,na:h,oa:y,ya:A,ga:u,qa:r,acceleration:m,Ta:z,pa:d,Ia:b});ya("ready",a)}}}l.Ra=function(a){var b=a.target;b.removeEventListener("load",this.o,!1);b.removeEventListener("error",this.o,!1);b=this.i.indexOf(b);0<=b&&("error"===a.type&&this.i.splice(b,1),this.j--);0===this.j&&Ea(this)};
l.updateAndDraw=function(){0===this.A&&U(this.g);if(2!=this.A){var a=this.g;a.i.save();a.i.scale(a.Ba,a.Ba);for(var b=0;b<a.j.length;b++){var d=a.j[b];if(d.fa)for(var c=0;c<d.fa.length;c++)ua(a,d.fa.get(c));ua(a,d.h)}a.i.restore()}};l.play=function(){this.A=0};l.pause=function(){this.A=1};l.stop=function(){this.A=2;var a=this.g;a.j.length=0;for(var b=a.o=0;b<a.g.Ha;b++)U(a)};l.reset=function(){Z(this);this.g=null;ya("request-reload",this)};
ca.Object.defineProperties(W,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return Aa}}});customElements.define("gwd-particles",W);}).call(this);
